spring.application.name=movie-app-server

spring.datasource.url=jdbc:mysql://localhost:3306/movieapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
#Thay thế tên username và password trên MySQL của mình vào nha
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Thay bằng token của mình trên TMDB sau khi đăng kí được. Hoặc nếu không thì có thể dùng luôn token này cũng đưược.
tmdb.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMmEyNGJmZTM3MmJjNTNlMjI4OWJiYzA2ZmViNDI2MyIsIm5iZiI6MTc4MDIxMzg1MC4yNDgsInN1YiI6IjZhMWJlODVhNDI5MDlmNWE1ZDdmNzNiMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.tv08UHJ7sdOBbOMddcnr26wQhkyTQoFgcvnSjyUN3GU
tmdb.base-url=https://api.themoviedb.org/3


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true