### Lấy dữ liệu phim bằng TMDB ID (Sync Movie)
POST http://localhost:8080/api/v1/admin/sync/movie
Content-Type: application/json

{
  "tmdbId": 533535,
  "videoUrl": "https://www.w3schools.com/html/mov_bbb.mp4",
  "premium": false
}

### Lấy dữ liệu phim bộ bằng TMDB ID (Sync TV Series)
POST http://localhost:8080/api/v1/admin/sync/tv
Content-Type: application/json

{
  "tmdbId": 94997
}